apiVersion: v1
data:
  alertmanager.yaml.gz: H4sIAAAAAAAA/7xSy07DMBC8+ytWPSKV8BCXSHxAv4BjtDUbZyU/wnqdqlLFtyMnUFKJCk5cZ2d3xjN2Pu3RtwZAKCc/UaccKBVt4SkYSUVpGVriiaSFTSzebwyAk1TGbn+s4y1EDJRHtFTJdSsv+A+LAAHVDiQzpZLQk2i9AM/vsNnFPu3iwHvWJKeXyn1N7lvygKwtPN7lM8JRSSb0s+dqdiTUFXr/MBheLnZSfPW2BUVxpN3ayxYyTSSsx2rkgBI5uhPHPhmAnIpYusoHK6xs0RsAeitLppe5rB76uz78UfbT5X+ormqCi5KuiX+VP+dd4fMvUAqjR12aaEhtMx8PGNGRNDbFnl1zc6th9OYjAAD//xIx++qkAgAA
kind: Secret
metadata:
  creationTimestamp: "2023-12-06T17:04:21Z"
  labels:
    managed-by: prometheus-operator
  name: alertmanager-monitoring-kube-prometheus-alertmanager-generated
  namespace: monitoring
  ownerReferences:
  - apiVersion: monitoring.coreos.com/v1
    blockOwnerDeletion: true
    controller: true
    kind: Alertmanager
    name: monitoring-kube-prometheus-alertmanager
    uid: eb042dd3-b5ac-47f0-8360-edf875b8554a
  resourceVersion: "1204"
  uid: 4bff62cf-a265-418c-888e-a375bdb5c599
type: Opaque
